name: app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.0.0
  design_system:
    path: ../design_system

  # FilledStacks
  stacked: ^2.2.5
  stacked_services: ^0.8.13

  # Caching
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^4.2.1
    
  # Firebase
  firebase_core: ^1.6.0

  animations: ^2.0.1
  injectable: ^1.5.0
  twitch_api: #^0.4.0
    path: ../../../flutter_projects/twitch_api_flutter
  cached_network_image: ^3.1.0
  webview_flutter: ^2.0.12
  loading_overlay: ^0.3.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.1.1
  hive_generator: ^1.1.0
  stacked_generator: ^0.5.1

flutter:
  uses-material-design: true

  assets:
    - resources/icons/

  fonts:
    - family: Nunito
      fonts:
        - asset: packages/design_system/resources/fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: packages/design_system/resources/fonts/Nunito-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: packages/design_system/resources/fonts/Nunito-Light.ttf
          weight: 300
        - asset: packages/design_system/resources/fonts/Nunito-LightItalic.ttf
          style: italic
          weight: 300
        - asset: packages/design_system/resources/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: packages/design_system/resources/fonts/Nunito-Italic.ttf
          style: italic
          weight: 400
        - asset: packages/design_system/resources/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: packages/design_system/resources/fonts/Nunito-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: packages/design_system/resources/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: packages/design_system/resources/fonts/Nunito-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: packages/design_system/resources/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: packages/design_system/resources/fonts/Nunito-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: packages/design_system/resources/fonts/Nunito-Black.ttf
          weight: 900
        - asset: packages/design_system/resources/fonts/Nunito-BlackItalic.ttf
          style: italic
          weight: 900