name: app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  lottie: ^1.2.1
  animations: ^2.0.1
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.0.0
  loading_overlay: ^0.3.0
  flutter_typeahead: ^3.2.1
  design_system:
    path: ../design_system

  # FilledStacks
  stacked: ^2.2.5
  stacked_services: ^0.8.13

  # Caching
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^4.2.1

  # Google
  firebase_core: ^1.6.0
  firebase_storage: ^10.0.5
  firebase_messaging: ^10.0.8
  cloud_firestore: ^2.5.3
  google_mobile_ads: ^0.13.5

  # Network
  twitch_api:
    path: ../twitch_api

  # Utils
  intl: ^0.17.0
  injectable: ^1.5.0
  url_launcher: ^6.0.12
  webview_flutter: ^2.0.14

  # Media
  image_picker: ^0.8.4+2
  cached_network_image: ^3.1.0
  flutter_native_image: ^0.0.6+1

  # Localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build: ^2.1.0
  build_runner: ^2.1.2
  hive_generator: ^1.1.0
  stacked_generator: ^0.5.2
  flutter_native_splash: ^1.3.1
  flutter_launcher_icons: ^0.9.2  

flutter:
  uses-material-design: true

  assets:
    - resources/icons/
    - resources/lottie/

  fonts:
    - family: Nunito
      fonts:
        - asset: packages/design_system/resources/fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: packages/design_system/resources/fonts/Nunito-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: packages/design_system/resources/fonts/Nunito-Light.ttf
          weight: 300
        - asset: packages/design_system/resources/fonts/Nunito-LightItalic.ttf
          style: italic
          weight: 300
        - asset: packages/design_system/resources/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: packages/design_system/resources/fonts/Nunito-Italic.ttf
          style: italic
          weight: 400
        - asset: packages/design_system/resources/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: packages/design_system/resources/fonts/Nunito-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: packages/design_system/resources/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: packages/design_system/resources/fonts/Nunito-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: packages/design_system/resources/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: packages/design_system/resources/fonts/Nunito-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: packages/design_system/resources/fonts/Nunito-Black.ttf
          weight: 900
        - asset: packages/design_system/resources/fonts/Nunito-BlackItalic.ttf
          style: italic
          weight: 900

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "resources/logo/logo.png"

flutter_native_splash:
  ios: true
  android: true
  background_image: resources/splash/splash-screen.png
  android_gravity: fill
  ios_content_mode: scaleAspectFill