// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjefKNo0G_Qe0jMb0dIlYopHu8g47IvN0',
    appId: '1:832640888153:web:6db6bdcfc16bf9a0d7b048',
    messagingSenderId: '832640888153',
    projectId: 'streamertime-app',
    authDomain: 'streamertime-app.firebaseapp.com',
    storageBucket: 'streamertime-app.appspot.com',
    measurementId: 'G-ERCWMW649V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ7n4qvS_Nu_Er2Rj4KLZHd0ju8ur62D0',
    appId: '1:832640888153:android:e06be970849c1e6cd7b048',
    messagingSenderId: '832640888153',
    projectId: 'streamertime-app',
    storageBucket: 'streamertime-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC61bDAjZXBUeuj8cLZU8H6DSgX3x0LAsA',
    appId: '1:832640888153:ios:139174ab2fbcd0b1d7b048',
    messagingSenderId: '832640888153',
    projectId: 'streamertime-app',
    storageBucket: 'streamertime-app.appspot.com',
    iosClientId: '832640888153-2t7jofi7e52tvklp912nj2elpa52kpj3.apps.googleusercontent.com',
    iosBundleId: 'com.jlima.streamup',
  );
}
